name: brick_supabase
description: Supabase connector for Brick, a data persistence library. Includes annotations, adapter, model, and provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_supabase
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.4.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  brick_core:
    path: ../brick_core
  collection: ">=1.15.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  supabase:
    path: ../../../supabase-flutter/packages/supabase

dev_dependencies:
  lints:
  test:
