name: brick_supabase_generators
description: Code generation library for the Supabase providers, models, and adapters in Brick
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_supabase_generators
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <7.0.0"
  brick_build:
    path: ../brick_build
  brick_core:
    path: ../brick_core
  brick_json_generators:
    path: ../brick_json_generators
  brick_supabase:
    path: ../brick_supabase
  build: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.0 <3.0.0"
  source_gen: ">=1.2.2 <2.0.0"

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  lints:
  test:
